name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v4

      - name: Install dependencies
        run: npm install

      #- name: Build application
      #  run: npm run build

      - name: Copy application to EC2
        uses: appleboy/scp-action@v1
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "build/"
          target: "/home/ubuntu/news-app"

      - name: SSH to EC2 and run application
        uses: appleboy/ssh-action@v2
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /home/ubuntu/news-app
            npm run dev

