name: Deploying

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: executing remote ssh commands using ssh key
        uses: appleboy/ssh-action@master
        with:
          SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
          REMOTE_HOST: ec2-13-127-183-253.ap-south-1.compute.amazonaws.com
          REMOTE_USER: ubuntu
          TARGET: /home/ubuntu/news-app
          script: sh deploy.sh
